# text overlays
CRITICAL_ALERTS_TEXT_OVERLAY = 'Critical Alerts'
DEFAULT_TEXT_OVERLAY = 'Default'
# timer overlays
DEBUFFS_TIMER_OVERLAY = 'Debuffs'
OTHER_BUFFS_TIMER_OVERLAY = 'Other Buffs'
SELF_BUFFS_TIMER_OVERLAY = 'Self Buffs'
SHORT_DURATION_BUFFS_TIMER_OVERLAY = 'Short Duration Buffs'
SHORT_DURATION_DEBUFFS_TIMER_OVERLAY = 'Short Duration Debuffs'
