# stdlib
from enum import Enum


class ColorPalette(Enum):
    BRIGHT_YELLOW = '#FFFFFF00'
    BRIGHT_RED = '#FFFF0000'
    BRIGHT_BLUE = '#FF0000FF'
    DARK_AQUA = '#FF008AA5'
    DARK_PINK = '#FFE20085'
    DARK_PURPLE = '#FF990099'
    DARK_BROWN = '#FF874219'
    DARK_BLUE = '#FF0048AF'
    DARK_RED = '#FF800000'
    DARK_ORANGE = '#FFC17003'
    DARK_GREEN = '#FF006D00'
    DARK_GREY = '#FF7A7A7A'
    DARK_YELLOW = '#FFB5A809'
    LIGHT_BLUE = '#FF697CC1'
    LIGHT_GREY = '#FFDBDBDB'
    FULLY_TRANSPARENT = '#00000000'
    TRANSPARENT_BLACK = '#C4000000'
    BLACK = '#FF000000'
    WHITE = '#FFFFFFFF'

    def __str__(self):
        return self.value


# alert colors
CRITICAL_ALERT_COLOR = ColorPalette.BRIGHT_RED
DEFAULT_ALERT_COLOR = ColorPalette.BRIGHT_YELLOW

# effect colors
ABSORB_EFFECT_COLOR = ColorPalette.DARK_BROWN
CHARM_EFFECT_COLOR = ColorPalette.DARK_AQUA
DAMAGE_SHIELD_EFFECT_COLOR = ColorPalette.DARK_BROWN
DETRIMENTAL_EFFECT_COLOR = ColorPalette.DARK_RED
DOT_EFFECT_COLOR = ColorPalette.DARK_ORANGE
HASTE_EFFECT_COLOR = ColorPalette.DARK_GREEN
HC_AC_EFFECT_COLOR = ColorPalette.DARK_YELLOW
HEAL_EFFECT_COLOR = ColorPalette.LIGHT_BLUE
ILLUSION_EFFECT_COLOR = ColorPalette.DARK_PINK
LULL_EFFECT_COLOR = ColorPalette.DARK_BLUE
MANA_EFFECT_COLOR = ColorPalette.DARK_BLUE
MEZ_EFFECT_COLOR = ColorPalette.DARK_PINK
MOVEMENT_SPEED_EFFECT_COLOR = ColorPalette.DARK_PURPLE
REGEN_EFFECT_COLOR = ColorPalette.DARK_AQUA
RESIST_EFFECT_COLOR = ColorPalette.DARK_RED
ROOT_EFFECT_COLOR = ColorPalette.DARK_BROWN
SLOW_EFFECT_COLOR = ColorPalette.DARK_PURPLE
SNARE_EFFECT_COLOR = ColorPalette.DARK_PURPLE
STAT_EFFECT_COLOR = ColorPalette.DARK_ORANGE
VISION_EFFECT_COLOR = ColorPalette.DARK_GREY

# status colors
EFFECT_WORN_OFF_COLOR = ColorPalette.BRIGHT_BLUE
